# Generated by Django 3.1.4 on 2020-12-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nsiOkato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11, verbose_name='Код ОКАТО')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование по ОКАТО')),
                ('parent', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nsiOkdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='Код ОКПД')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование по ОКПД')),
                ('parent', models.CharField(max_length=8, null=True)),
                ('section', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nsiOkdp2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='Код ОКПД2')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование по ОКПД2')),
                ('parent', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nsiOkeiGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Код группы')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование группы')),
            ],
        ),
        migrations.CreateModel(
            name='nsiOkeiSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, verbose_name='Код раздела')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование раздела')),
            ],
        ),
        migrations.CreateModel(
            name='nsiOkfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='Код ОКФС')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование по ОКФС')),
            ],
        ),
        migrations.CreateModel(
            name='nsiOkogu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, verbose_name='Код ОКОГУ')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование по ОКОГУ')),
                ('parent', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nsiOkopf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Код ОКОПФ')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование по ОКОГУ')),
                ('parent', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nsiOktmo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11, verbose_name='Код ОКФС')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование по ОКФС')),
                ('parent', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nsiOkv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Код валюты')),
                ('digitalCode', models.CharField(max_length=100, verbose_name='Цифровой код валюты')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование валюты')),
                ('shortName', models.CharField(max_length=500, null=True, verbose_name='Наименование валюты')),
            ],
        ),
        migrations.CreateModel(
            name='nsiOkved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='Код ОКВЕД')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование по ОКВЕД')),
                ('parent', models.CharField(max_length=15, null=True)),
                ('section', models.CharField(max_length=1, verbose_name='Раздел')),
                ('subsection', models.CharField(max_length=2, null=True, verbose_name='Подраздел')),
            ],
        ),
        migrations.CreateModel(
            name='nsiOkved2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='Код ОКВЕД2')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование по ОКВЕД2')),
                ('parent', models.CharField(max_length=15, null=True)),
                ('section', models.CharField(max_length=1, verbose_name='Раздел')),
            ],
        ),
        migrations.CreateModel(
            name='nsiOkei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Код ОКЕИ')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование по ОКЕИ')),
                ('symbol', models.CharField(max_length=30, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokeigroup', verbose_name='Группа')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokeisection', verbose_name='Раздел')),
            ],
        ),
    ]
