# Generated by Django 3.1.4 on 2020-12-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nsiFz233type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Код вида организации')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование вида организации')),
            ],
        ),
        migrations.CreateModel(
            name='nsiIkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код ИКЮЛ')),
                ('name', models.CharField(max_length=255, verbose_name='Наименвоание вида юридического лица')),
            ],
        ),
        migrations.CreateModel(
            name='nsiOkpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код ОКПО')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Наименование ОКПО')),
            ],
        ),
        migrations.CreateModel(
            name='nsiPPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11, verbose_name='Код ППО')),
                ('name', models.CharField(max_length=2000, verbose_name='Наименование ППО')),
            ],
        ),
        migrations.CreateModel(
            name='nsiTimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.IntegerField(default=0, verbose_name='Смещение отностельно MSK')),
                ('name', models.CharField(max_length=100, verbose_name='Название временной зоны')),
            ],
        ),
        migrations.CreateModel(
            name='nsiTypeContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип контакта')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Полное имя')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное наименвоание')),
                ('ogrn', models.CharField(max_length=13, verbose_name='ОГРН')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('legalAddress', models.TextField(max_length=2000, null=True, verbose_name='Юридический адрес')),
                ('postalAddress', models.TextField(max_length=2000, null=True, verbose_name='Почтовый адрес')),
                ('okato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokato', verbose_name='ОКАТО')),
                ('okfs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokfs', verbose_name='ОКФС')),
                ('okopf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokopf', verbose_name='ОКОПФ')),
                ('okpo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokpo', verbose_name='ОКПО')),
                ('oktmo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.nsioktmo', verbose_name='ОКТМО')),
                ('timeZone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.nsitimezone', verbose_name='Временная зона')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=300, null=True, verbose_name='Имя')),
                ('middleName', models.CharField(max_length=300, null=True, verbose_name='Отчество')),
                ('lastName', models.CharField(max_length=300, null=True, verbose_name='Фамилия')),
                ('inn', models.CharField(max_length=12, null=True, verbose_name='ИНН')),
            ],
        ),
        migrations.CreateModel(
            name='PersonContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.person', verbose_name='Физическое лицо')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsitypecontact', verbose_name='Тип контакта')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationOkved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMain', models.BooleanField(default=False, verbose_name='Основной')),
                ('okved2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokved2', verbose_name='ОКВЭД2')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.organization', verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.organization', verbose_name='Организация')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsitypecontact', verbose_name='Тип контакта')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.person', verbose_name='Физическое лицо')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationNumber', models.CharField(max_length=28, verbose_name='Реестровый номер')),
                ('registryStatus', models.BooleanField(default=True, null=True, verbose_name='Включен в реестр заказчиков')),
                ('addedToRegistryDate', models.DateTimeField(null=True, verbose_name='Дата включения в реестр')),
                ('removedFromRegistryDate', models.DateTimeField(null=True, verbose_name='Дата исключения из реестра')),
                ('ikul_assigmentDate', models.DateTimeField(verbose_name='Дата присвоения ИКЮЛ')),
                ('authority', models.IntegerField(default=0, verbose_name='Полномочия организации')),
                ('isPPO', models.BooleanField(default=False, verbose_name='Принадлежность к ППО')),
                ('PPO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsippo', verbose_name='ППО')),
                ('capitalStockAgencies', models.ManyToManyField(related_name='OrgCap', to='main_app.Organization', verbose_name='Информация о юридических лицах, перечисленных в п. 1, 2 ч. 2 ст. 1 223-ФЗ')),
                ('contactPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.person', verbose_name='Контактное лицо')),
                ('fz233type', models.ManyToManyField(to='main_app.nsiFz233type')),
                ('grantedUsersWoAttorney', models.ManyToManyField(to='main_app.Employee', verbose_name='Лица имеющие право действовать без доверенности')),
                ('ikul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiikul', verbose_name='ИКЮЛ')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.organization', verbose_name='Организация')),
            ],
        ),
    ]
