# Generated by Django 3.1.4 on 2020-12-18 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201219_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='registration_date',
            field=models.DateTimeField(null=True, verbose_name='Дата постановки на учет'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PPO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.nsippo', verbose_name='ППО'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='capitalStockAgencies',
            field=models.ManyToManyField(null=True, related_name='OrgCap', to='main_app.Organization', verbose_name='Информация о юридических лицах, перечисленных в п. 1, 2 ч. 2 ст. 1 223-ФЗ'),
        ),
    ]
