# Generated by Django 3.1.4 on 2020-12-18 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201219_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.BooleanField(default=True, verbose_name='Актуальная')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='type_org',
            field=models.CharField(choices=[('L', 'Юридическое лицо'), ('P', 'Физическое лицо')], default='L', max_length=1, verbose_name='Тип органзиации'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Supllier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationNumber', models.CharField(max_length=28, verbose_name='Реестровый номер')),
                ('registryStatus', models.BooleanField(default=True, null=True, verbose_name='Включен в реестр поставщиков')),
                ('addedToRegistryDate', models.DateTimeField(null=True, verbose_name='Дата регистрации в ЕИС')),
                ('removedFromRegistryDate', models.DateTimeField(null=True, verbose_name='Дата исключения из ЕИС')),
                ('contactPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.person', verbose_name='Контактное лицо')),
                ('etp', models.ManyToManyField(null=True, to='main_app.ETP', verbose_name='Электронная площадка')),
                ('grantedUsersWoAttorney', models.ManyToManyField(to='main_app.Employee', verbose_name='Лица имеющие право действовать без доверенности')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.organization', verbose_name='Организация')),
            ],
        ),
        migrations.AddField(
            model_name='etp',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.organization', verbose_name='Организация ЭТП'),
        ),
    ]
