# Generated by Django 3.1.4 on 2020-12-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201219_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsiokved',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Наименование по ОКВЕД'),
        ),
    ]
