# Generated by Django 3.1.4 on 2020-12-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201219_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='registrationNumber',
            field=models.CharField(max_length=28, unique=True, verbose_name='Реестровый номер'),
        ),
        migrations.AlterField(
            model_name='nsifz233type',
            name='code',
            field=models.CharField(max_length=4, unique=True, verbose_name='Код вида организации'),
        ),
        migrations.AlterField(
            model_name='nsiikul',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код ИКЮЛ'),
        ),
        migrations.AlterField(
            model_name='nsiokato',
            name='code',
            field=models.CharField(max_length=11, unique=True, verbose_name='Код ОКАТО'),
        ),
        migrations.AlterField(
            model_name='nsiokdp',
            name='code',
            field=models.CharField(max_length=8, unique=True, verbose_name='Код ОКПД'),
        ),
        migrations.AlterField(
            model_name='nsiokdp2',
            name='code',
            field=models.CharField(max_length=8, unique=True, verbose_name='Код ОКПД2'),
        ),
        migrations.AlterField(
            model_name='nsiokei',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Код ОКЕИ'),
        ),
        migrations.AlterField(
            model_name='nsiokeigroup',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Код группы'),
        ),
        migrations.AlterField(
            model_name='nsiokeisection',
            name='code',
            field=models.CharField(max_length=1, unique=True, verbose_name='Код раздела'),
        ),
        migrations.AlterField(
            model_name='nsiokfs',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Код ОКФС'),
        ),
        migrations.AlterField(
            model_name='nsiokogu',
            name='code',
            field=models.CharField(max_length=7, unique=True, verbose_name='Код ОКОГУ'),
        ),
        migrations.AlterField(
            model_name='nsiokopf',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Код ОКОПФ'),
        ),
        migrations.AlterField(
            model_name='nsiokpo',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Код ОКПО'),
        ),
        migrations.AlterField(
            model_name='nsioktmo',
            name='code',
            field=models.CharField(max_length=11, unique=True, verbose_name='Код ОКФС'),
        ),
        migrations.AlterField(
            model_name='nsiokv',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Код валюты'),
        ),
        migrations.AlterField(
            model_name='nsiokved',
            name='code',
            field=models.CharField(max_length=15, unique=True, verbose_name='Код ОКВЕД'),
        ),
        migrations.AlterField(
            model_name='nsiokved',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование по ОКВЕД'),
        ),
        migrations.AlterField(
            model_name='nsippo',
            name='code',
            field=models.CharField(max_length=11, unique=True, verbose_name='Код ППО'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(max_length=12, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='supllier',
            name='registrationNumber',
            field=models.CharField(max_length=28, unique=True, verbose_name='Реестровый номер'),
        ),
    ]
