# Generated by Django 3.1.4 on 2020-12-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201219_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationNumber', models.CharField(max_length=11, verbose_name='Регистрационный номер договора закупки')),
                ('url', models.URLField(null=True, verbose_name='Ссылка на ЕИС')),
                ('createDateTime', models.DateTimeField(verbose_name='Дата создания договора')),
                ('fulfillmentDate', models.DateTimeField(verbose_name='Дата исполнения договора')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='Сумма договора')),
                ('sumInfo', models.CharField(max_length=2000, verbose_name='Информация о сумме')),
                ('deliveryState', models.CharField(max_length=2000, null=True, verbose_name='Место поставки субъект РФ ')),
                ('deliveryRegion', models.CharField(max_length=2000, null=True, verbose_name='Место поставки регион РФ ')),
                ('deliveryAddress', models.CharField(max_length=2000, null=True, verbose_name='Адрес поставки')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokv', verbose_name='Валюта')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer', verbose_name='Организатор')),
                ('deliveryOkato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokato', verbose_name='Место поставки регион РФ ')),
                ('placer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.organization', verbose_name='Организации, создавшая сведения договора закупки')),
                ('purchaseInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.purchasenotice', verbose_name='Информация о извещении')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.supllier', verbose_name='Поставщик')),
            ],
        ),
        migrations.CreateModel(
            name='ContractLotPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinalNumber', models.IntegerField(verbose_name='Позиция')),
                ('qty', models.IntegerField(default=1, verbose_name='Количество')),
                ('additionalInfo', models.CharField(max_length=2000, verbose_name='Дополнительная информация')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.contract', verbose_name='Контракт')),
                ('okei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokei', verbose_name='единица измерения')),
                ('okpd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokdp', verbose_name='ОКПД')),
                ('okpd2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokdp2', verbose_name='ОКПД2')),
                ('okved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokved', verbose_name='ОКВЭД')),
                ('okved2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokved2', verbose_name='ОКВЭД2')),
            ],
        ),
        migrations.RenameModel(
            old_name='lot',
            new_name='PurchaseNoticeLot',
        ),
        migrations.RenameModel(
            old_name='lotPosition',
            new_name='PurchaseNoticeLotPosition',
        ),
        migrations.CreateModel(
            name='DishonestSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationNumber', models.CharField(max_length=7, verbose_name='Регистрационный номер')),
                ('url', models.URLField(null=True, verbose_name='Ссылка на ЕИС')),
                ('includeReasonInfo', models.CharField(max_length=2000, verbose_name='Основания для включение в реест')),
                ('includeReason', models.CharField(max_length=2000, verbose_name='Причина для включение в реест')),
                ('includeDate', models.DateTimeField(verbose_name='Дата включения в реестр')),
                ('excludeDate', models.DateTimeField(verbose_name='Дата исключения из реестр')),
                ('topSecret', models.BooleanField(default=False, verbose_name='Является гостайной')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.contract', verbose_name='Контракт')),
                ('contractItems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.contractlotposition', verbose_name='Позиции')),
                ('controlAgency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DS_controlAgency', to='main_app.organization', verbose_name='Уполномоченный орган')),
                ('placer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.organization', verbose_name='Организация подавшая сведения')),
                ('purchaseInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.purchasenotice', verbose_name='Закупка')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DS_supplier', to='main_app.supllier', verbose_name='Поставщик')),
            ],
        ),
        migrations.CreateModel(
            name='ContractLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinalNumber', models.IntegerField(verbose_name='Позиция в контракте')),
                ('contractDataSubject', models.CharField(max_length=2000, verbose_name='Наименование предмета договора')),
                ('initialSum', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='Начальная цена договора')),
                ('maxContractPrice', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='Максимальная цена договора')),
                ('exchangeRate', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Курс')),
                ('exchangeRateDate', models.DateField(verbose_name='Дата курса')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.contract', verbose_name='Контракт')),
                ('curency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokv', verbose_name='Валюта')),
                ('okpd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokdp', verbose_name='ОКПД2')),
                ('okpd2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokdp2', verbose_name='ОКПД2')),
                ('okved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokved', verbose_name='ОКВЭД2')),
                ('okved2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokved2', verbose_name='ОКВЭД2')),
            ],
        ),
    ]
