# Generated by Django 3.1.4 on 2020-12-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201219_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='capitalStockAgencies',
            field=models.ManyToManyField(related_name='OrgCap', to='main_app.Organization', verbose_name='Информация о юридических лицах, перечисленных в п. 1, 2 ч. 2 ст. 1 223-ФЗ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fz233type',
            field=models.ManyToManyField(to='main_app.nsiFz233type'),
        ),
        migrations.AlterField(
            model_name='supllier',
            name='etp',
            field=models.ManyToManyField(to='main_app.ETP', verbose_name='Электронная площадка'),
        ),
    ]
