# Generated by Django 3.1.4 on 2020-12-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20201219_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationOkved2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMain', models.BooleanField(default=False, verbose_name='Основной')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Контракт', 'verbose_name_plural': 'Контракты'},
        ),
        migrations.AlterModelOptions(
            name='contractlot',
            options={'verbose_name': 'Лот контракта', 'verbose_name_plural': 'Лоты контракта'},
        ),
        migrations.AlterModelOptions(
            name='contractlotposition',
            options={'verbose_name': 'Позиция лота контракта', 'verbose_name_plural': 'Позиции лота контракта'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='dishonestsupplier',
            options={'verbose_name': 'Недобросовоестный поставщик', 'verbose_name_plural': 'Недобросовоестные поставщики'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='etp',
            options={'verbose_name': 'Электронная торговая площадка', 'verbose_name_plural': 'Электронные торговые площадки'},
        ),
        migrations.AlterModelOptions(
            name='nsiikul',
            options={'verbose_name': 'ИКЮЛ', 'verbose_name_plural': 'ИКЮЛ'},
        ),
        migrations.AlterModelOptions(
            name='nsiokato',
            options={'verbose_name': 'ОКАТО', 'verbose_name_plural': 'ОКАТО'},
        ),
        migrations.AlterModelOptions(
            name='nsiokdp',
            options={'verbose_name': 'ОКПД', 'verbose_name_plural': 'ОКПД'},
        ),
        migrations.AlterModelOptions(
            name='nsiokdp2',
            options={'verbose_name': 'ОКПД2', 'verbose_name_plural': 'ОКПД2'},
        ),
        migrations.AlterModelOptions(
            name='nsiokei',
            options={'verbose_name': 'ОКЕИ', 'verbose_name_plural': 'ОКЕИ'},
        ),
        migrations.AlterModelOptions(
            name='nsiokfs',
            options={'verbose_name': 'ОКФС', 'verbose_name_plural': 'ОКФС'},
        ),
        migrations.AlterModelOptions(
            name='nsiokogu',
            options={'verbose_name': 'ОКОГУ', 'verbose_name_plural': 'ОКОГУ'},
        ),
        migrations.AlterModelOptions(
            name='nsiokopf',
            options={'verbose_name': 'ОКОПФ', 'verbose_name_plural': 'ОКОПФ'},
        ),
        migrations.AlterModelOptions(
            name='nsiokpo',
            options={'verbose_name': 'ОКПО', 'verbose_name_plural': 'ОКПО'},
        ),
        migrations.AlterModelOptions(
            name='nsioktmo',
            options={'verbose_name': 'ОКТМО', 'verbose_name_plural': 'ОКТМО'},
        ),
        migrations.AlterModelOptions(
            name='nsiokv',
            options={'verbose_name': 'ОК валют', 'verbose_name_plural': 'ОК валют'},
        ),
        migrations.AlterModelOptions(
            name='nsiokved',
            options={'verbose_name': 'ОКВЭД', 'verbose_name_plural': 'ОКВЭД'},
        ),
        migrations.AlterModelOptions(
            name='nsiokved2',
            options={'verbose_name': 'ОКВЭД2', 'verbose_name_plural': 'ОКВЭД2'},
        ),
        migrations.AlterModelOptions(
            name='nsippo',
            options={'verbose_name': 'ППО', 'verbose_name_plural': 'ППО'},
        ),
        migrations.AlterModelOptions(
            name='nsitimezone',
            options={'verbose_name': 'Временная зона', 'verbose_name_plural': 'Временные зоны'},
        ),
        migrations.AlterModelOptions(
            name='nsitypecontact',
            options={'verbose_name': 'Тип контакта', 'verbose_name_plural': 'Типы контактов'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Физическое лицо', 'verbose_name_plural': 'Физические лица'},
        ),
        migrations.AlterModelOptions(
            name='purchasenotice',
            options={'verbose_name': 'Извещение', 'verbose_name_plural': 'Извещения'},
        ),
        migrations.AlterModelOptions(
            name='purchasenoticelot',
            options={'verbose_name': 'Лот извещения', 'verbose_name_plural': 'Лоты извещений'},
        ),
        migrations.AlterModelOptions(
            name='purchasenoticelotposition',
            options={'verbose_name': 'Позиция лота извещения', 'verbose_name_plural': 'Позиции лота извещений'},
        ),
        migrations.AlterModelOptions(
            name='purchaseplandata',
            options={'verbose_name': 'План закупок', 'verbose_name_plural': 'Планы закупок'},
        ),
        migrations.AlterModelOptions(
            name='purchaseplandataitems',
            options={'verbose_name': 'Позиция плана закупок', 'verbose_name_plural': 'Позиции плана закупок'},
        ),
        migrations.AlterModelOptions(
            name='purchaseplandataitemsposition',
            options={'verbose_name': 'Элемент плана закупок', 'verbose_name_plural': 'Элементы плана закупок'},
        ),
        migrations.AlterModelOptions(
            name='supllier',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='fz233type',
        ),
        migrations.RemoveField(
            model_name='organizationokved',
            name='okved2',
        ),
        migrations.AddField(
            model_name='organizationokved',
            name='okved',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokved', verbose_name='ОКВЭД'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseplandataitemsposition',
            name='purchasePlanDataItems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.purchaseplandataitems', verbose_name='Элемент плана закупки'),
        ),
        migrations.DeleteModel(
            name='nsiFz233type',
        ),
        migrations.AddField(
            model_name='organizationokved2',
            name='okved2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nsiokved2', verbose_name='ОКВЭД2'),
        ),
        migrations.AddField(
            model_name='organizationokved2',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.organization', verbose_name='Организация'),
        ),
    ]
