# Generated by Django 3.1.4 on 2020-12-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20201219_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_organization', to='main_app.organization', verbose_name='Организация'),
        ),
    ]
