# Generated by Django 3.1.4 on 2020-12-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20201219_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ikul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_organization', to='main_app.nsiikul', verbose_name='ИКЮЛ'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='okato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_nsiOkato', to='main_app.nsiokato', verbose_name='ОКАТО'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='okfs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_okfs', to='main_app.nsiokfs', verbose_name='ОКФС'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='okopf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_okopf', to='main_app.nsiokopf', verbose_name='ОКОПФ'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='okpo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_okpo', to='main_app.nsiokpo', verbose_name='ОКПО'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='oktmo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_oktmo', to='main_app.nsioktmo', verbose_name='ОКТМО'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='timeZone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_timeZone', to='main_app.nsitimezone', verbose_name='Временная зона'),
        ),
    ]
