from django.contrib import admin
from .models import *
import inspect

admin.site.register(nsiOkfs)
admin.site.register(nsiOktmo)
admin.site.register(nsiOkato)
admin.site.register(nsiOkogu)
admin.site.register(nsiTimeZone)
admin.site.register(nsiOkopf)
admin.site.register(nsiOkei)
admin.site.register(nsiOkdp)
admin.site.register(nsiOkdp2)
admin.site.register(nsiOkved)
admin.site.register(Customer)
admin.site.register(nsiOkved2)
admin.site.register(nsiOkpo)
admin.site.register(nsiTypeContact)
admin.site.register(nsiIkul)
admin.site.register(nsiPPO)
admin.site.register(Organization)
admin.site.register(OrganizationOkved)
admin.site.register(OrganizationOkved2)
admin.site.register(OrganizationContacts)
admin.site.register(Person)
admin.site.register(PersonContacts)
admin.site.register(Employee)
admin.site.register(ETP)
admin.site.register(Supllier)
admin.site.register(PurchasePlanData)
admin.site.register(PurchasePlanDataItemsPosition)
admin.site.register(PurchasePlanDataItems)
admin.site.register(PurchaseNotice)
admin.site.register(PurchaseNoticeLot)
admin.site.register(PurchaseNoticeLotPosition)
admin.site.register(Contract)
admin.site.register(ContractLot)
admin.site.register(ContractLotPosition)